on:
  push:
    branches:
      - dev
name: ğŸš€ Deploy to production
jobs:
  web-deploy:
    name: ğŸ‰ Prod Deployment
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code1
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 5.134.14.49
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}